### PR TITLE
Request for JC 17.12.2018

### PR DESCRIPTION
**Pull request by senait2018**
Request for JC 17.12.18

### CODE REVIEW

**Comment by senait2018** [comment]
Request for JC 17.12.18

**Comment by senait2018** [comment]
Request for JC 17.12.18

**Comment by senait2018** [comment]
Request for JC 17.12.2018

**Comment by markrobinsonuzh** [comment]
And also submit a new pull request (and be sure to refresh your fork). I'll close this one.

**Comment by senait2018** [comment]
Changed to this paper:
 [Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing on JSTOR]

**Pull request closed without merging**
